<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_SubmissionValue</name>
   <tag></tag>
   <elementGuidId>a5967685-a9a8-436a-80a6-4124916b6956</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[text()='${label}']/following-sibling::td[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
